
export const sample_foods:any[]=[
    {id:'1',
    name:'Cheese Pizza',
    cookTime:'10-20',
    price:10,
    favorite: false,
    origins:['Italy'],
    stars: 4.5,
    imageUrl:'assets/food-1.jpg',
    tags:['FastFood','Pizza','Lunch'],},
    {id:'2',
    name:'Meatball',
    cookTime:'20-30',
    price:20,
    favorite: true,
    origins:['China'],
    stars: 4.7,
    imageUrl:'assets/food-2.jpg',
    tags:['SlowFood','Lunch'],},
    {id:'3',
    name:'Classic Hamburger',
    cookTime:'10-15',
    price:5,
    favorite: false,
    origins:['Germany'],
    stars: 3.5,
    imageUrl:'assets/food-3.jpg',
    tags:['FastFood','Hamburger','Lunch'],},
    {id:'4',
    name:'Fried Potatoes',
    cookTime:'15-20',
    price:15,
    favorite: true,
    origins:['French'],
    stars: 4.5,
    imageUrl:'assets/food-4.jpg',
    tags:['FastFood','Fry','Dinner'],},
    {id:'5',
    name:'Chiken Soup',
    cookTime:'30-40',
    price:11,
    favorite: false,
    origins:['India'],
    stars: 3.0,
    imageUrl:'assets/food-5.jpg',
    tags:['FastFood','Soup','Dinner'],},
    {id:'6',
    name:'Vegetables Pizza',
    cookTime:'20-30',
    price:15,
    favorite: true,
    origins:['Italy'],
    stars: 4.0,
    imageUrl:'assets/food-6.jpg',
    tags:['FastFood','Pizza','Lunch'],},
    {id:'7',
    name:'Couscous with meat',
    cookTime:'50-60',
    price:12,
    favorite: false,
    origins:['Tunisia'],
    stars: 4.5,
    imageUrl:'assets/food-7.jpg',
    tags:['SlowFood','Tunisia','Lunch'],},
    {id:'8',
    name:'Spegatti',
    cookTime:'40-50',
    price:15,
    favorite: false,
    origins:['Italy'],
    stars: 4,
    imageUrl:'assets/food-8.jpg',
    tags:['SlowFood','spegatti','Lunch'],},
    {id:'9',
    name:'Maki Sushi ',
    cookTime:'20-30',
    price:10,
    favorite: false,
    origins:['Japon'],
    stars: 3,
    imageUrl:'assets/food-9.jpg',
    tags:['FastFood','sushi','Dinner'],},
    {id:'10',
    name:'Paella',
    cookTime:'40-45',
    price:50,
    favorite: true,
    origins:['Espagne'],
    stars: 5,
    imageUrl:'assets/food-10.jpg',
    tags:['SlowFood','Paella','Dinner'],},
    {id:'11',
    name:'Onion Soup',
    cookTime:'20-25',
    price:15,
    favorite: false,
    origins:['French'],
    stars: 2,
    imageUrl:'assets/food-11.jpg',
    tags:['FastFood','Onion Soup','Dinner'],},
    {id:'12',
    name:'Veggie burger',
    cookTime:'15-25',
    price:25,
    favorite: false,
    origins:['Germany'],
    stars: 2,
    imageUrl:'assets/food-12.jpg',
    tags:['FastFood','Veggie burger','Dinner'],},
    {id:'13',
    name:'Couscous with fish',
    cookTime:'40-45',
    price:50,
    favorite: true,
    origins:['Tunisia'],
    stars: 5,
    imageUrl:'assets/food-13.jpg',
    tags:['SlowFood','couscous','Lunch'],},
    {id:'14',
    name:'Inari Sushi',
    cookTime:'30-35',
    price:35,
    favorite: true,
    origins:['Japon'],
    stars: 4.5,
    imageUrl:'assets/food-14.jpg',
    tags:['FastFood','sushi','Dinner'],},
    {id:'15',
    name:'Spaghetti Bolognese',
    cookTime:'40-45',
    price:45,
    favorite: false,
    origins:['Italy'],
    stars: 3.5,
    imageUrl:'assets/food-15.jpg',
    tags:['SlowFood','Spaghetti Bolognese','Dinner'],},
]
export const sample_tags:any[]=[
    {name:'All',count:15},
    {name:'Lunch',count:7},
    {name:'Dinner',count:8},
    {name:'SlowFood',count:6},
    {name:'FastFood',count:9},
    
]

export const sample_users:any[]=[
    {
    name:"Hanen Chaari",
    email: "hanenchaari46@gmail.com",
    password:"hanouna",
    address: "Sfax",
    isAdmin:true,
   },
   {
    name:"AyatAllah Zekri",
    email: "zekriayatallah@gmail.com",
    password:"ayouta",
    address:"Sfax",
    isAdmin:false,
   }
]